### ISSUE TITLE
[FEATURE] Add Two Legged OAuth generalized provider AuthN pattern

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql#474]
### **Feature Description**
Introduce support for a standard two-legged OAuth 2.0 pattern in StackQL providers. This authentication mechanism allows the exchange of long-lived secrets for short-lived, scoped bearer tokens. The feature should be generalized for any provider supporting OAuth 2.0 and extensible to accommodate custom variations, such as account-level and workspace-level tokens in Databricks.  

### **Example(s)**  
Sample StackQL configuration for a Databricks provider:  

```yaml
config:
  auth:
    type: oauth2
    tokenurl: https://accounts.cloud.databricks.com/oidc/accounts/${DATABRICKS_ACCOUNT_ID}/v1/token
    scope: all-apis
    grant_type: client_credentials
    clientidvar: DATABRICKS_CLIENT_ID
    clientsecretvar: DATABRICKS_CLIENT_SECRET
```
the token request would return something like:

```json
{
  "access_token": "eyJraWQiOiJkYTA4ZTVjZ…",
  "token_type": "Bearer",
  "expires_in": 3600
}
```
The `access_token` is then just used as a bearer token in any subsequent API requests to the endpoints defined in `servers` in the service spec.  The configuration should support similar flows for other providers, maintaining flexibility and consistency.  

#### **Golang Libraries**  
1. **[golang/oauth2](https://pkg.go.dev/golang.org/x/oauth2)**  
   - A widely-used library for handling OAuth 2.0 flows.  
   - Provides built-in support for `client_credentials` grant type and token management.  
   - Offers extensibility for adding custom parameters or handling provider-specific behavior.  

2. **[dexidp/dex](https://github.com/dexidp/dex)**  
   - A more advanced library for OAuth 2.0 and OIDC, though it might be overkill for simple two-legged flows.  

3. **Custom Implementation with `net/http` and JSON**  
   - A lightweight approach using Golang's standard `net/http` package to handle token requests.  
   - Libraries such as `json` and `mapstructure` can parse and map response payloads.  

4. **[go-resty/resty](https://github.com/go-resty/resty)**  
   - Simplifies HTTP requests with built-in retries, JSON support, and ease of handling headers and form data.
